insert into public.site_settings (
  id,
  site_name,
  site_tagline,
  hero_badge,
  hero_title,
  hero_description,
  hero_primary_cta,
  hero_secondary_cta,
  hero_video_url,
  topbar_enabled,
  topbar_variant,
  topbar_text,
  topbar_cta_label,
  topbar_cta_url,
  topbar_expires_at,
  hero_highlight_one,
  hero_highlight_two,
  hero_highlight_three,
  contact_email,
  contact_phone,
  whatsapp_url,
  address,
  opening_hours,
  seo_title,
  seo_description,
  seo_keywords,
  seo_canonical_url,
  seo_og_image_url,
  footer_text,
  updated_at
)
values (
  1,
  'Nova Forza',
  'Fuerza, disciplina y progreso real para quienes entrenan en serio.',
  'Entrenamiento premium en Lima',
  'El poder de tu progreso comienza aqui',
  'Entrenamiento de fuerza de elite con asesoria personalizada en un ambiente disenado para resultados reales en Lima.',
  'Reserva tu prueba',
  'Ver planes',
  '/video/video.mp4',
  true,
  'promotion',
  'Matricula gratis por tiempo limitado para nuevos socios.',
  'Reserva tu prueba',
  '#contacto',
  timezone('utc', now()) + interval '30 day',
  'Planes claros para empezar, progresar y sostener resultados.',
  'Entrenadores que corrigen, acompanan y hacen seguimiento real.',
  'Sala premium local con horarios amplios y recogida en tienda.',
  'hola@novaforza.pe',
  '+51 987 654 321',
  'https://wa.me/51987654321',
  'Av. Progreso 245, zona comercial local',
  'Lunes a viernes de 6:00 a 22:00. Sabados de 8:00 a 14:00.',
  'Nova Forza | Gimnasio premium de fuerza y progreso real',
  'Web comercial de Nova Forza: planes claros, horarios amplios, asesoria cercana y una experiencia premium para entrenar con seriedad.',
  array['gimnasio premium', 'fuerza', 'planes de gimnasio', 'entrenamiento personalizado', 'nova forza'],
  'https://novaforza.pe',
  null,
  'Nova Forza es un gimnasio local orientado a fuerza, progreso real y una experiencia seria y cercana.',
  timezone('utc', now())
)
on conflict (id) do update set
  site_name = excluded.site_name,
  site_tagline = excluded.site_tagline,
  hero_badge = excluded.hero_badge,
  hero_title = excluded.hero_title,
  hero_description = excluded.hero_description,
  hero_primary_cta = excluded.hero_primary_cta,
  hero_secondary_cta = excluded.hero_secondary_cta,
  hero_video_url = excluded.hero_video_url,
  topbar_enabled = excluded.topbar_enabled,
  topbar_variant = excluded.topbar_variant,
  topbar_text = excluded.topbar_text,
  topbar_cta_label = excluded.topbar_cta_label,
  topbar_cta_url = excluded.topbar_cta_url,
  topbar_expires_at = excluded.topbar_expires_at,
  hero_highlight_one = excluded.hero_highlight_one,
  hero_highlight_two = excluded.hero_highlight_two,
  hero_highlight_three = excluded.hero_highlight_three,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  whatsapp_url = excluded.whatsapp_url,
  address = excluded.address,
  opening_hours = excluded.opening_hours,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  seo_keywords = excluded.seo_keywords,
  seo_canonical_url = excluded.seo_canonical_url,
  seo_og_image_url = excluded.seo_og_image_url,
  footer_text = excluded.footer_text,
  updated_at = excluded.updated_at;

insert into public.leads (name, email, phone, message, source, status, metadata)
values
  (
    'Lucia Romero',
    'lucia@example.com',
    '+51 999 112 233',
    'Quiero reservar una prueba y saber que plan me conviene si busco bajar grasa.',
    'seed',
    'new'::public.lead_status,
    '{"demo": true, "interest": "prueba"}'::jsonb
  ),
  (
    'Diego Flores',
    'diego@example.com',
    '+51 988 445 566',
    'Me interesa el plan Progreso para entrenar fuerza antes de ir a trabajar.',
    'seed',
    'contacted'::public.lead_status,
    '{"demo": true, "interest": "plan progreso"}'::jsonb
  ),
  (
    'Paola Rivas',
    'paola@example.com',
    null,
    'Ya hice la visita guiada y quiero volver para cerrar mi inscripcion este fin de semana.',
    'seed',
    'closed'::public.lead_status,
    '{"demo": true, "interest": "inscripcion"}'::jsonb
  );
